name: MLOps CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✅ Run Model Training
        run: |
          python src/train.py

      - name: 🧪 Run Evaluation
        run: |
          python src/evaluate.py

      - name: 🚀 Test API Endpoint (Optional)
        run: |
          pip install httpx
          uvicorn api.app:app --host 0.0.0.0 --port 8000 &
          sleep 5
          python -c "import httpx; r = httpx.post('http://localhost:8000/predict', json={'sepal_length':5.1,'sepal_width':3.5,'petal_length':1.4,'petal_width':0.2}); print('API response:', r.json())"
